<?xml version="1.0"?>
<!DOCTYPE classmates_info [
<!ELEMENT classmates_info (student+)>
<!ELEMENT student (Student_ID, Name, Gender, Phone, Address)>
<!ELEMENT Student_ID (#PCDATA) >
<!ELEMENT Name (#PCDATA) >
<!ELEMENT Gender (#PCDATA) >
<!ELEMENT Phone (#PCDATA) >
<!ELEMENT Address (#PCDATA) >
]>

<classmates_info>
	<student>
	<Student_ID>410820001</Student_ID>
	<Name>王01</Name>
	<Gender>女</Gender>
	<Phone>0928000001</Phone>
	<Address>地球01</Address>
	</student>
	<student>
	<Student_ID>410820002</Student_ID>
	<Name>王02</Name>
	<Gender>男</Gender>
	<Phone>0928000002</Phone>
	<Address>地球02</Address>
	</student>
	<student>
	<Student_ID>410820003</Student_ID>
	<Name>王03</Name>
	<Gender>女</Gender>
	<Phone>0928000003</Phone>
	<Address>地球03</Address>
	</student>
	<student>
	<Student_ID>410820004</Student_ID>
	<Name>王04</Name>
	<Gender>男</Gender>
	<Phone>0928000004</Phone>
	<Address>地球04</Address>
	</student>
	<student>
	<Student_ID>410820005</Student_ID>
	<Name>王05</Name>
	<Gender>女</Gender>
	<Phone>0928000005</Phone>
	<Address>地球05</Address>
	</student>
	<student>
	<Student_ID>410820006</Student_ID>
	<Name>王06</Name>
	<Gender>男</Gender>
	<Phone>0928000006</Phone>
	<Address>地球06</Address>
	</student>
</classmates_info>